### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by fooxx** [pgarba/King#18]
Severity  Code  Description  Project  File  Line  Suppression State
Error    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBUSB10
    linked by target "king" in directory C:/Users/Reactive/source/repos/King1

**Comment by pgarba** [comment]
CMake domain
